### ISSUE TITLE
Migrate to c++17

### ISSUE THREAD

**Issue by AaronWebster** [google/emboss#53]
I see a lot of TODOs referencing c++17.  Are we good to resolve them as c++17 support is [pretty much there](https://libcxx.llvm.org/Status/Cxx17.html)?

**Comment by reventlov** [comment]
We won't be requiring C++17 until at least 2027, so emphatically NO.

The support promise is that we support a particular version of C++ until its successor has been out for at least 10 years.  This is stricter than the [absl's policy](https://abseil.io/about/compatibility#what-we-promise) because Emboss targets embedded platforms, whose toolchains historically lag.
